### PR TITLE
Fix code to match coding standards required by doctrine/mongodb-odm team

### PR DESCRIPTION
**Pull request by robholmes**

### CODE REVIEW

**Comment by robholmes** [comment]
@gistya Can you merge this pull request to hopefully enable @malarzm to merge your PR 970 on doctrine/mongodb-odm please?

**Comment by malarzm** [comment]
For the record I'm not able to merge PRs in ODM, I'm just helping voluntary :)

**Comment by robholmes** [comment]
@malarzm Ok no problem, I was just making a bad assumption, but thank you for your help :)

**Comment by gistya** [comment]
OK I have merged the pull request. Let me know if I need to do anything further. 
- Jon Gilbert - 
- @gistya -

**Comment by robholmes** [comment]
@gistya Thank you!

**Pull request merged**
